name: dawey
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  double_back_to_close: ^1.0.2+mit
  # timeline_tile: ^1.0.0
#  timelines: ^0.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  android_intent: ^0.3.7+7
  # flutter_facebook_login: ^3.0.0
  flutter_html:
  flutter_polyline_points: ^0.2.4
  geocoder: ^0.2.1
  get: ^3.22.2
  google_maps_flutter: ^0.5.31
  google_maps_place_picker: null
  #  google_sign_in: null
  http: ^0.12.2
  image_cropper: ^1.1.2
  image_picker: ^0.6.0+9
  mime: ^0.9.7
  pin_code_fields: ^3.0.1
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.7.10


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/ic_splash.jpeg
    - assets/images/ic_upper.png
    - assets/images/ic_lower.png
    - assets/images/ic_login.png
    - assets/images/ic_man.png
    - assets/images/ic_register.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/ic_icon_login.png
    - assets/images/ic_icon_signup.png
    - assets/images/ic_my_order.png
    - assets/images/dashboard.png
    - assets/images/home.png
    - assets/images/menu.png
    - assets/images/ic_contact.png
    - assets/images/ic_faq.png
    - assets/images/ic_medical_center.png
    - assets/images/ic_my_task.png
    - assets/images/ic_privacy_policy.png
    - assets/images/ic_share.png
    - assets/images/ic_about.png
    - assets/images/ic_home_small.png
    - assets/images/ic_about_us.png
    - assets/images/icon_my_order.png
    - assets/images/ic_calendar.png
    - assets/images/dashboard_contant.png
    - assets/images/profile.png
    - assets/images/profile.jpeg
    - assets/images/ic_dash_image.png
    - assets/images/ic_location_pin.jpeg
    - assets/images/ic_pin.png
    - assets/images/map_image.jpeg
    - assets/images/ic_delivery_man.png
    - assets/images/ic_lang.png
    - assets/images/ic_us.png
    - assets/images/ic_ar.png
    - assets/images/label.png
    - assets/images/logout.png
    - assets/images/iconprofile.png
    - assets/images/ic_camera.png
    - assets/images/ic_add.png
    - assets/images/home.gif
    - assets/images/logo.png
    - assets/images/enter.png
    - assets/images/dr_image.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
